db_url = "https://plc1212-python-firebase-default-rtdb.asia-southeast1.firebasedatabase.app/"

[firebase]
type = "service_account"
project_id = "plc1212-python-firebase"
private_key_id = "..." 
# Sử dụng dấu ngoặc kép ba để dán nguyên văn khóa từ file JSON
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASC... (Copy toàn bộ nội dung khóa vào đây)
...
-----END PRIVATE KEY-----
"""
client_email = "..."
client_id = "..."
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "..."